// <auto-generated />
using AfleveringUge8.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AfleveringUge8.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20190413132245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AfleveringUge8.Models.Translation", b =>
                {
                    b.Property<int>("TranslationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Croatian")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Danish")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("German")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Italian")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Norwegian")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Spanish")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Swedish")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TranslationID");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
